Task 1
veronikaboyko/CloudStorageBot pull request #3
Opened 2024-04-18 11:44 UTC by veronikaboyko

2024-05-05 11:16 UTC, vpyzhyanov commented
На повторную проверку задача передана спустя 10 дней. Это очень много.

2024-05-05 11:23 UTC, vpyzhyanov commented on .gitignore
> +/src/main/java/org/example/usersData/
Прошу соблюдать правила хорошего тона. Тогда всегда код ревью будет приятным для всех участников и наиболее эффективным!

**Не исправлено!!!!**

2024-05-05 11:30 UTC, vpyzhyanov commented on src/main/java/org/example/bot/TelegramBot.java
> +            e.printStackTrace();
недостаточно - означает, что стек **нужен** (не надо его убирать, он очень удобен для разбора ошибок), но не хватает сообщения об ошибке.

Для вывода ошибок в лог, есть специальный поток `System.err`

2024-05-05 11:59 UTC, vpyzhyanov commented on src/main/java/org/example/bot/MessageHandler.java
> +                    final State currentUserState = usersCommand.get(chatId).currentState;
Очень грубое нарушение инкапсуляции

2024-05-05 11:59 UTC, vpyzhyanov commented on src/main/java/org/example/bot/MessageHandler.java
> +                    final State currentUserState = usersCommand.get(chatId).currentState;
3 раза делается одно и то же действие `usersCommand.get(chatId)`

2024-05-05 11:59 UTC, vpyzhyanov commented on src/main/java/org/example/bot/MessageHandler.java
> +                            usersCommand.get(chatId).currentState = State.GOT_DATA_FROM_USER;
даже 4(((

2024-05-05 11:59 UTC, vpyzhyanov commented on src/main/java/org/example/bot/MessageHandler.java
> +                            usersCommand.get(chatId).currentState = State.GOT_DATA_FROM_USER;
Правильнее и удобнее было выделить отдельный класс, который будет управлять состоянием

Почему вообще работа с состояниями происходит в `MessageHandler`? Состояние должно меняться внутри команд. Этот класс лишь должен вызывать нужный обработчик команды. Вы даже сами это написали

> определяет, какая команда была введена пользователем, и вызывает ее обработчик

, но, почему-то, сами это правило нарушаете

2024-05-05 11:59 UTC, vpyzhyanov commented on src/main/java/org/example/bot/MessageHandler.java
> +                        //а тут могут быть кейсы, если команда может хранить 3,4,5 и тд состояний.
тут вы практически прямым текстом говорите "Мы не собираемся соблюдать принцип открытой закрытости (SOLID)", следовательно расширять или изменять вашу программу будет очень тяжело

2024-05-05 11:59 UTC, vpyzhyanov commented on src/main/java/org/example/command/CreateCommand.java
> +        String[] arguments = messageFromUser.split("\\s+");
я надеялся, что вы догадаетесь это абсолютно одинаковое для всех команд действие тоже вынести в абстрактный класс

2024-05-05 11:59 UTC, vpyzhyanov commented on src/main/java/org/example/command/CreateCommand.java
> +            throw new IOException(e.getMessage());
зачем это делать? Чтобы потерять оригинальный стек? А это ценная информация!

1. Сообщение об ошибке должно быть в тексте исключения, а не только в логе.
2. В конструктор IOException нужно передать ещё и оригинальное исключение, чтобы сформировать полный стек.
3. Неправильное место для вывода лога. В лог будет выводить там, где будет обрабатывать исключение.

2024-05-05 11:59 UTC, vpyzhyanov commented on src/main/java/org/example/command/ListFilesCommand.java
> +            throw new IOException("Внутрення ошибка при работе с файлами.");
дублирование кода. Ну и лог нужен точно не в этом месте, а на уровень выше.

2024-05-05 11:59 UTC, vpyzhyanov commented on src/main/java/org/example/commands/StatebleCommands/EditFileCommand.java
> +    private UserStatement currentUserStatement = UserStatement.STATE_1;
согласен. Просто попало под шаблон с копированием констант

2024-05-05 12:10 UTC, vpyzhyanov commented on src/main/java/org/example/internal/FileManager.java
> +                .renameTo(new File(String.valueOf(Paths.get(getFileNameByID(chatId), newName))));
Не исправлено. Всё равно всё кучу раз дублируется.

Да и ещё создаётся String -> Path -> String. Либо сразу строку создавайте, либо используйте сразу Path, он гораздо удобнее, чем строка

2024-05-05 12:17 UTC, vpyzhyanov commented on src/main/java/org/example/internal/FileManager.java
> +        Path directoryPath = Paths.get(ConstantManager.USER_DATA_DIRECTORY, "user_" + chatId);
кучу раз дублируется один и тот же путь. Вынесите это в метод хотя бы.

2024-05-05 12:17 UTC, vpyzhyanov commented on src/main/java/org/example/internal/FileManager.java
> +        String curr_user_directory = String.valueOf(Paths.get(getFileNameByID(chatId)));
Никому не нужная конвертация данных: создаётся String -> Path -> String. Либо сразу строку создавайте, либо используйте сразу Path, он гораздо удобнее, чем строка

2024-05-05 12:17 UTC, vpyzhyanov commented on src/main/java/org/example/internal/FileManager.java
> +        new File(curr_user_directory, oldName).renameTo(new File(curr_user_directory, newName));
лучше так: filePath.toFile()

2024-05-05 12:17 UTC, vpyzhyanov commented on src/main/java/org/example/internal/FileManager.java
> +        String curr_user_directory = String.valueOf(Paths.get(getFileNameByID(chatId)));
CamelCase пожалуйста

2024-05-05 12:17 UTC, vpyzhyanov commented on src/main/java/org/example/internal/FileManager.java
> +            System.out.println("Произошла ошибка в переименовывании");
лучше бы сделали полноценную обработку ошибок

2024-05-05 12:21 UTC, vpyzhyanov commented on src/main/java/org/example/internal/FileManager.java
> +            return "Файл не найден";
Никогда больше так не делайте.

![image](https://github.com/veronikaboyko/CloudStorageBot/assets/71599019/8cfff8e9-c72b-4b2b-81ef-728a1de1518f)

1. **Потеряли всю необходимую информацию их исходного исключения** (самое страшное)
2. Не добавили никакой новой информации (и так понятно что FileNotFoundException означает, что файл не найден)
3. Написали аж 4 строчки лишнего кода

Просто уберите этот catch

2024-05-05 12:24 UTC, vpyzhyanov commented on src/main/java/org/example/internal/FileManager.java
> +            return "Файл не найден";
А вообще в случаях **обработки** исключений надо поступать так:

![image](https://github.com/veronikaboyko/CloudStorageBot/assets/71599019/d0712922-2792-481f-bbc4-1f92251e3c01)

Создаём новое исключение, добавляем всю информацию из нашего контекста и передаём перехваченное исключение для полноты стека и сообщений об ошибке

2024-05-05 12:30 UTC, vpyzhyanov commented on src/main/java/org/example/state/CommandWithState.java
> +public class CommandWithState
теперь название не отражает суть. Это `CommandState`, т.к. сам класс командой не является, а состоянием является.

2024-05-05 12:30 UTC, vpyzhyanov commented on src/main/java/org/example/state/CommandWithState.java
> +        if (!new MessageHandler().isCommand(currentCommand))
вы ведь понимаете, что вызов этого конструктора сожрёт всю вашу память? Вы каждый раз заполняете список всех команд.

2024-05-05 12:30 UTC, vpyzhyanov commented on src/test/java/FileManagerTest.java
> +    @Test(expected = IllegalArgumentException.class)
Используйте `Assert.assertThrows(...)`

2024-05-05 12:34 UTC, vpyzhyanov commented on src/test/java/org/example/internal/FileManagerTest.java
> +            assertEquals("Файла с таким названием не существует!", e.getMessage());
Используйте `Assert.assertThrows(...)`

2024-05-05 12:34 UTC, vpyzhyanov commented on src/test/java/FileManagerTest.java
> +        fileManager.createFile("testDeleteFile.txt", TEST_CHAT_ID);
Иногда приходится это делать. Тем более это тренирует абстрактное мышление. Класс называется `FileManager`, значит он потенциально может уметь работать с любой директорией. Получается изменив класс под тесты, вы сделаете его более универсальным и расширяемым.

2024-05-05 12:37 UTC, vpyzhyanov commented on src/test/java/FileManagerTest.java
> +        assertTrue(Files.readString(getFilePath(TEST_FILE_NAME)).contains(newText));
- А если файл был перезаписан?
- А если строка добавляется в начало?
- А если добавляется ещё куча лишней информации?

И этот список можно продолжать

2024-05-05 12:39 UTC, vpyzhyanov requested changes
Не все замечания исправлены. И появились новые. 

Тесты посмотрю чуть позже

2024-05-05 12:39 UTC, vpyzhyanov commented on src/test/java/org/example/internal/FileManagerTest.java
> +            assertTrue(Files.readString(getFilePath(TEST_FILE_NAME)).contains(newText));
Дублирую неисправленное замечание

> проверка некорректная, тут должен быть assertEquals

2024-05-06 13:07 UTC, YuriProduction commented on src/main/java/org/example/state/CommandWithState.java
> +        if (!new MessageHandler().isCommand(currentCommand))
А сборщик мусора разве не придет на помощь после выполнения конструктора?

2024-05-06 17:48 UTC, YuriProduction commented on src/main/java/org/example/bot/MessageHandler.java
> +                    final State currentUserState = usersCommand.get(chatId).currentState;
Зачем здесь инкапсуляция? Нам нужно поменять поле объекта, через сеттер или напрямую, разницы нет

2024-05-06 17:48 UTC, YuriProduction commented on src/main/java/org/example/bot/MessageHandler.java
> +                    final State currentUserState = usersCommand.get(chatId).currentState;
+

2024-05-06 17:48 UTC, YuriProduction commented on src/main/java/org/example/bot/MessageHandler.java
> +                            usersCommand.get(chatId).currentState = State.GOT_DATA_FROM_USER;
+

2024-05-06 17:50 UTC, YuriProduction commented on src/main/java/org/example/bot/MessageHandler.java
> +                            usersCommand.get(chatId).currentState = State.GOT_DATA_FROM_USER;
+

2024-05-06 17:53 UTC, YuriProduction commented on src/main/java/org/example/bot/MessageHandler.java
> +                        //а тут могут быть кейсы, если команда может хранить 3,4,5 и тд состояний.
Ничего не понял, расширение - просто дописать один case. Где тут какие проблемы...

2024-05-06 18:00 UTC, YuriProduction commented on src/main/java/org/example/command/CreateCommand.java
> +        String[] arguments = messageFromUser.split("\\s+");
+

2024-05-06 18:13 UTC, YuriProduction commented on src/main/java/org/example/command/ListFilesCommand.java
> +            throw new IOException("Внутрення ошибка при работе с файлами.");
+

2024-05-06 18:23 UTC, YuriProduction commented on src/main/java/org/example/internal/FileManager.java
> +        Path directoryPath = Paths.get(ConstantManager.USER_DATA_DIRECTORY, "user_" + chatId);
+

2024-05-06 18:24 UTC, YuriProduction commented on src/main/java/org/example/internal/FileManager.java
> +        String curr_user_directory = String.valueOf(Paths.get(getFileNameByID(chatId)));
+

2024-05-06 18:25 UTC, YuriProduction commented on src/main/java/org/example/internal/FileManager.java
> +        String curr_user_directory = String.valueOf(Paths.get(getFileNameByID(chatId)));
+

2024-05-07 00:12 UTC, veronikaboyko commented on src/main/java/org/example/command/CreateCommand.java
> +            throw new IOException(e.getMessage());
+++

2024-05-07 00:18 UTC, veronikaboyko commented on src/main/java/org/example/internal/FileManager.java
> +            return "Файл не найден";
+++

2024-05-07 00:36 UTC, veronikaboyko commented on .gitignore
> +/src/main/java/org/example/usersData/
+++

2024-05-07 00:39 UTC, veronikaboyko commented on src/main/java/org/example/bot/TelegramBot.java
> +            e.printStackTrace();
стек счас в MessageHandler'e выводится есть

2024-05-07 00:44 UTC, veronikaboyko commented on src/main/java/org/example/internal/FileManager.java
> +            System.out.println("Произошла ошибка в переименовывании");
в MessageHandler'e обработка

2024-05-07 00:45 UTC, veronikaboyko commented on src/main/java/org/example/internal/FileManager.java
> +            return "Файл не найден";
только не поняла, зачем новое исключение

2024-05-07 00:46 UTC, veronikaboyko commented on src/test/java/FileManagerTest.java
> +    @Test(expected = IllegalArgumentException.class)
+++

2024-05-07 00:47 UTC, veronikaboyko commented on src/test/java/FileManagerTest.java
> +        fileManager.createFile("testDeleteFile.txt", TEST_CHAT_ID);
вообще нельзя, но если вам хочется, то можно))

2024-05-07 01:07 UTC, veronikaboyko commented on src/test/java/org/example/internal/FileManagerTest.java
> +            assertTrue(Files.readString(getFilePath(TEST_FILE_NAME)).contains(newText));
+++

2024-05-07 01:09 UTC, veronikaboyko commented on src/test/java/org/example/internal/FileManagerTest.java
> +            assertEquals("Файла с таким названием не существует!", e.getMessage());
+++

2024-05-07 19:14 UTC, vpyzhyanov commented
> Не получилось заигнорировать файлы?

Если вы думаете, что замечания по Git можно не исправлять, то это не так. Файлы нужно заигнорировать

2024-05-07 19:23 UTC, vpyzhyanov commented on src/main/java/org/example/internal/FileManager.java
> +            return "Файл не найден";
В разных случаях по разному. Если нет необходимости создавать исключение (обработка не требуется), то не нужно этого делать, просто бросаем исключение дальше.

А если нужно обработать исключение, то выбросить надо уже новое исключение, сохранив информацию о предыдущем. В моём примере меняется обрабатываемое исключение на **необрабатываемое**.

2024-05-07 19:25 UTC, vpyzhyanov commented on src/test/java/FileManagerTest.java
> +        assertTrue(Files.readString(getFilePath(TEST_FILE_NAME)).contains(newText));
Не исправлено

2024-05-07 19:26 UTC, vpyzhyanov commented on src/main/java/org/example/bot/MessageHandler.java
> +                    final State currentUserState = usersCommand.get(chatId).currentState;
публичное поле - недопустимо ни при каких обстоятельствах, неважно есть настоящая инкапсуляция или нет.
геттеры и сеттеры - это конвенция разработчиков и надо её придерживаться. Тем более так гораздо проще контролировать доступ и делать дополнительные проверки, если они будут нужны.

2024-05-07 19:32 UTC, vpyzhyanov commented on src/main/java/org/example/bot/MessageHandler.java
> +                            usersCommand.get(chatId).currentState = State.GOT_DATA_FROM_USER;
обсудили этот момент в ЛС

> 1. замечание не про проверку состояния. С ней всё ок, смотрим состояние - выбираем нужный обработчик. Замечание именно про изменение состояния.
Например, при обработке команды случилась ошибка. Должно ли измениться состояние? Наверное нет, ведь логичнее попросить пользователя ввести правильную команду ещё раз находясь в том же состоянии. Кто должен заниматься этой обработкой ошибок? Ей должна заниматься команда!

> 2. Вся ответственность по работе с состоянием сейчас находится в MessageHandler, значит класс взял на себя слишком много. Освободите его это лишнего груза ответственности. Пусть делает только свою работу.

> Задача MessageHandler - не общаться с пользователем и командами, а передавать управление нужной команде. Как телефонистка раньше соединяла двух абонентов, чтобы они могли поговорить друг с другом. Тут точно так же. Команда общается с пользователем, а пользователь с командой. MessageHandler не должен ничего перехватывать. Он может только отправить что-то вроде "команда не найдена". И то можно сделать отдельную команду для обработки неизвестных команд

2024-05-07 19:33 UTC, vpyzhyanov commented on src/main/java/org/example/bot/MessageHandler.java
> +                        //а тут могут быть кейсы, если команда может хранить 3,4,5 и тд состояний.
если кратко: для расширения функционала вам придётся изменять код. На маленьких проектах - это не сложно, но на больших проектах с тысячами классов - это сделать намного сложнее.
Чтобы лучше понять надо прям погрузиться в принципы SOLID и изучить их.

2024-05-07 19:33 UTC, vpyzhyanov commented on src/main/java/org/example/bot/MessageHandler.java
> +                        //а тут могут быть кейсы, если команда может хранить 3,4,5 и тд состояний.
Придумал пример похожий на ваш случай:
Изначально класс умеет обрабатывать 1 и 2 аргумента. Для этого мы сделали перегрузку, написали 2 метода (один с 1 аргументом, другой с двумя).
Потом заказчик захотел обрабатывать 3 аргумента. Мы пишем ещё один метод.
... И вот заказчик не знает меры и запрашивает уже 999 аргументов. А тем временем мы замаялись добавлять методы и поддерживать их все.
Если бы мы воспользовались принципом единой ответственности, то мы бы изначально написали метод, который принимает произвольное количество аргументов и дальше бы ничего не делали.

2024-05-07 19:37 UTC, vpyzhyanov commented on src/main/java/org/example/internal/FileManager.java
> +        new File(curr_user_directory, oldName).renameTo(new File(curr_user_directory, newName));
плохо, что через строки. Надо было сделать так: `File currentUserDirectory = getPathToUserDir(chatId).toFile();`, а метод `getFileNameByID` вообще удалить. Он дублирует метод getPathToUserDir

2024-05-07 19:40 UTC, vpyzhyanov commented on src/main/java/org/example/state/CommandWithState.java
> +        if (!new MessageHandler().isCommand(currentCommand))
Нет, он придёт только когда ваша память закончится (на самом деле это зависит от сборщика мусора, но он всё равно может прийти далеко не сразу)

2024-05-07 19:46 UTC, vpyzhyanov commented
Договорились с Юрием понизить сложность и писать замечания более конкретно.

2024-05-07 20:19 UTC, vpyzhyanov requested changes
Радует, что при написании тестов использовали материал лекции.

Как исправите оставшиеся замечания, сразу можете мёржить. Задача принята

2024-05-07 20:19 UTC, vpyzhyanov commented on src/test/java/org/example/internal/FileManagerTest.java
> +    public static final String WORKING_DIRECTORY = "src/test/java/org/example/temp/";
Опять та же ошибка. Никаких ресурсов, и тем более, временных файлов, в директории с исходниками быть не должно. 

Во вторых настоящая временная папка вот: `String tmpdir = System.getProperty("java.io.tmpdir")`. А наиболее правильно делать [вот так](https://stackoverflow.com/questions/39317170/how-to-create-a-junit-temporaryfolder-with-subfolders).

2024-05-07 20:19 UTC, vpyzhyanov commented on src/test/java/org/example/internal/FileManagerTest.java
> +        fileManager.deleteFile("testCreateFile1.txt", TEST_CHAT_ID);
Если не используете TemporaryFolder, то это должно быть в блоке finally

2024-05-07 20:19 UTC, vpyzhyanov commented on src/test/java/org/example/internal/FileManagerTest.java
> +        assertTrue(exception.getMessage().contains("Неверное расширение файла. Допустимые расширения: txt, json, xml."));
Тест некорректен. Используйте assertEquals

2024-05-07 20:19 UTC, vpyzhyanov commented on src/test/java/org/example/internal/FileManagerTest.java
> +        assertTrue(exception.getMessage().contains("Файл с таким именем уже существует."));
Тест некорректен. Используйте assertEquals

2024-05-07 20:19 UTC, vpyzhyanov commented on src/test/java/org/example/internal/FileManagerTest.java
> +        assertTrue(fileManager.isValidFileName("test.txt"));
по хорошему надо проверить все допустимые расширения

2024-05-07 20:19 UTC, vpyzhyanov commented on src/test/java/org/example/internal/FileManagerTest.java
> +        assertFalse(fileManager.isValidFileName("test.jpg"));
было бы здорово, если бы тут было больше проверок. Особенно форматов, которые содержат корректный формат в подстроке, например `txtx`.

2024-05-07 20:19 UTC, vpyzhyanov commented on src/test/java/org/example/bot/MessageHandlerTest.java
> +        messageHandler = new MessageHandler();
тут тоже надо задавать временную директорию. ([ссылка](https://stackoverflow.com/questions/39317170/how-to-create-a-junit-temporaryfolder-with-subfolders))

1. Очистка мусора произойдёт автоматически
2. Тесты могут не иметь доступа к директории, где хранятся файлы пользователя.

2024-05-07 20:19 UTC, vpyzhyanov commented on src/test/java/org/example/bot/MessageHandlerTest.java
> +        messageHandler.handleUserMessage("/delete f.txt", TEST_CHAT_ID);
Если это очистка мусора, что она должна быть в блоке finally. Либо надо использовать `TemporaryFolder`

2024-05-07 20:19 UTC, vpyzhyanov commented on src/test/java/org/example/bot/MessageHandlerTest.java
> +        messageHandler.handleUserMessage("/delete f.txt", TEST_CHAT_ID);
аналогично

2024-05-07 20:19 UTC, vpyzhyanov commented on src/test/java/org/example/bot/MessageHandlerTest.java
> +        messageHandler.handleUserMessage("/delete f.txt", TEST_CHAT_ID);
аналогично

2024-05-09 10:16 UTC, YuriProduction commented on src/test/java/org/example/bot/MessageHandlerTest.java
> +        messageHandler.handleUserMessage("/delete f.txt", TEST_CHAT_ID);
+

2024-05-09 10:16 UTC, YuriProduction commented on src/test/java/org/example/bot/MessageHandlerTest.java
> +        messageHandler.handleUserMessage("/delete f.txt", TEST_CHAT_ID);
+

2024-05-09 10:16 UTC, YuriProduction commented on src/test/java/org/example/bot/MessageHandlerTest.java
> +        messageHandler.handleUserMessage("/delete f.txt", TEST_CHAT_ID);
+

2024-05-09 10:17 UTC, YuriProduction commented on src/test/java/org/example/internal/FileManagerTest.java
> +        assertFalse(fileManager.isValidFileName("test.jpg"));
+

2024-05-09 10:17 UTC, YuriProduction commented on src/test/java/org/example/internal/FileManagerTest.java
> +        assertTrue(fileManager.isValidFileName("test.txt"));
+

2024-05-09 10:18 UTC, YuriProduction commented on src/test/java/org/example/internal/FileManagerTest.java
> +        assertTrue(exception.getMessage().contains("Файл с таким именем уже существует."));
+

2024-05-09 10:19 UTC, YuriProduction commented on src/test/java/org/example/internal/FileManagerTest.java
> +        assertTrue(exception.getMessage().contains("Неверное расширение файла. Допустимые расширения: txt, json, xml."));
+

2024-05-09 10:19 UTC, YuriProduction commented on src/test/java/org/example/internal/FileManagerTest.java
> +        fileManager.deleteFile("testCreateFile1.txt", TEST_CHAT_ID);
+уже использую

2024-05-09 10:20 UTC, YuriProduction commented on src/test/java/org/example/internal/FileManagerTest.java
> +    public static final String WORKING_DIRECTORY = "src/test/java/org/example/temp/";
+

2024-05-11 19:29 UTC, merged